models/Room.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

class Room extends ActiveRecord
{
    public static function tableName()
    {
        return 'rooms'; // Name of the database table
    }

    public function rules()
    {
        return [
            [['name', 'description', 'capacity'], 'required'], // Both fields are required
            [['name'], 'string', 'max' => 255], // Name is a string with a maximum length of 255
            [['description'], 'string'], // Description is a text field
            [['capacity'], 'integer', 'min' => 1],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'capacity' => 'Capacity'
        ];
    }

    public function getBookings()
    {
        return $this->hasMany(Booking::className(), ['room_id' => 'id']);
    }

}

controllers/BookingController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\Booking;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\NotFoundHttpException;

class BookingController extends Controller
{
    public function actionIndex()
    {
        $bookings = Booking::find()->all();
        return $this->render('index', ['bookings' => $bookings]);
    }

    public function actionCreate($room_id = null)
    {
        $model = new Booking();

        if ($room_id) {
            $model->room_id = $room_id;
            $model->user_id = Yii::$app->user->id;
            $model->status = 'pending';
        }

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                if ($model->save()) {
                    return $this->redirect(['room/index']);
                }
            } else {
                Yii::error("Validation errors: " . json_encode($model->getErrors()));
            }
        }
        

        return $this->render('create', ['model' => $model]);
    }

    public function actionView($id)
    {
        $booking = $this->findModel($id);
        return $this->render('view', ['booking' => $booking]);
    }

    public function actionList($room_id)
    {
        $bookings = Booking::find()->where(['room_id' => $room_id])->all();

        return $this->render('list', ['bookings' => $bookings, 'room_id' => $room_id]);
    }

    public function actionApprove($id)
    {
        $booking = Booking::findOne($id);
        $rules = $booking->rules();
        if ($booking) {
            $booking->status = 'approved';
            $booking->save();
        }

        return $this->redirect(['list', 'room_id' => $booking->room_id]);
    }

    public function actionPending($id)
    {
        $booking = Booking::findOne($id);
        if ($booking) {
            $booking->status = 'pending';
            $booking->save();
        }

        return $this->redirect(['list', 'room_id' => $booking->room_id]);
    }

    // Helper method to find a Booking model
    protected function findModel($id)
    {
        if (($model = Booking::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested booking does not exist.');
    }
}

controllers/RoomController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Room;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\NotFoundHttpException;

class RoomController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['admin']
                    ],
                    [
                        'actions' => ['index', 'view'],
                        'allow' => true,
                        'roles' => ['@'], // Logged in users
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $rooms = Room::find()->all();
        return $this->render('index', ['rooms' => $rooms]);
    }

    public function actionView($id)
    {
        $room = $this->findModel($id);
        return $this->render('view', ['room' => $room]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionCreate()
    {
        $model = new Room();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $room = $this->findModel($id);

        if ($room->getBookings()->exists()) {
            Yii::$app->session->setFlash('error', 'Cannot delete the room because there are bookings associated with it.');
            return $this->redirect(['index']);
        }

        $room->delete();
        return $this->redirect(['index']);
    }



    // Helper method to find a Room model
    protected function findModel($id)
    {
        if (($model = Room::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested room does not exist.');
    }
}

views/room/create.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Room */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Create Room';
$this->params['breadcrumbs'][] = ['label' => 'Rooms', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="room-create">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="room-form">
        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
        <?= $form->field($model, 'capacity')->textInput(['type' => 'number']) ?>

        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/room/index.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $rooms app\models\Room[] */

$this->title = 'Rooms';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="room-index">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->user->can('admin')): ?>
        <p>
            <?= Html::a('Create Room', ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    <?php endif; ?>

    <?php foreach ($rooms as $room): ?>
        <div class="card" style="width: 18rem; margin: 50px 50px 50px 0px; float: left;">
            <div class="card-body">
                <h5 class="card-title"><?= Html::encode($room->name) ?></h5>
                <p class="card-title"><?= Html::encode($room->description) ?></p>
                <?php if (Yii::$app->user->can('admin')): ?>
                    <?= Html::a('View', ['view', 'id' => $room->id], ['class' => 'btn btn-primary btn-sm']) ?>
                    <?= Html::a('Update', ['update', 'id' => $room->id], ['class' => 'btn btn-warning btn-sm']) ?>
                    <?= Html::a('Delete', ['delete', 'id' => $room->id], ['class' => 'btn btn-danger btn-sm']) ?>
                    <?= Html::a('List Bookings', ['booking/list', 'room_id' => $room->id], ['class' => 'btn btn-info btn-sm']) ?>
                <?php endif; ?>

                <?php
                $userHasBooked = \app\models\Booking::find()
                    ->where(['room_id' => $room->id, 'user_id' => Yii::$app->user->id])
                    ->exists();

                if (Yii::$app->user->can('user')):
                    if (!$userHasBooked) {
                            echo Html::a('Book', ['booking/create', 'room_id' => $room->id], ['class' => 'btn btn-success btn-sm']);
                    } else {
                        echo Html::a('You have Booked this room', 'javascript:void(0);', ['class' => 'btn btn-success btn-sm disabled']);
                    }
                endif;
                ?>
            </div>
        </div>
    <?php endforeach; ?>


</div>

views/room/update.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Room */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Update Room: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Rooms', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>

<div class="room-update">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="room-form">
        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
        <?= $form->field($model, 'capacity')->textInput(['type' => 'number']) ?>

        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/room/view.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $room app\models\Room */

$this->title = $room->name;
$this->params['breadcrumbs'][] = ['label' => 'Rooms', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="room-view">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $room->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $room->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this room?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Room: <?= Html::encode($room->name) ?></h5>
            <p class="card-text">Description: <?= Html::encode($room->description) ?></p>
            <p class="card-text">Capacity: <?= Html::encode($room->capacity) ?></p>
        </div>
    </div>
</div>